// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/529023aca8fcf5fff3753d211251796732ae9dc1/reselect/reselect.d.ts
// Type definitions for reselect v2.0.2
// Project: https://github.com/rackt/reselect
// Definitions by: Ian Ker-Seymer <https://github.com/ianks>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

// see https://github.com/reactjs/reselect/pull/94